### ISSUE TITLE
Certain Spanish twitter pages are identified as English

### ISSUE THREAD

**Issue by xiaochengh** [google/cld3#10]
This is found in crbug.com/809243.

Repro twitter page: https://twitter.com/paurubio

Almost all tweets are Spanish, but it's still identified as English when Chrome tries to detect page language using CLD.

I'm also attaching Chrome's text dump that's passed to CLD for language detection: [dump.txt](https://github.com/google/cld3/files/1786392/dump.txt)

**Comment by jasonriesa** [comment]
Language ID for multilingual spans on multilingual pages is not supported by Chrome right now. CLD3 will return the most prevalent language it finds. Looking at your dump, there is mostly English text with some short Spanish text segments, so the model returns English. We don't do any special processing for Twitter.
