### ISSUE TITLE
Chromium Dependency

### ISSUE THREAD

**Issue by loretoparisi** [google/cld3#11]
Is it possible to avoid the dependency of Chromium? Is this needed for protobuf dependency only? If so it would be worth to add external libraries and a Makefile to compile cld3 directly without the Chromium overhead...

**Comment by edvakf** [comment]
Actually, it doesn't need Chromium to build any more, I think.
Neither https://github.com/Elizafox/cld3 nor https://github.com/Elizafox/cld3 needs it.

**Comment by loretoparisi** [comment]
@edvakf thank you to point this out. It would be great to have an official release as well that includes protobuf while removing the Chromium dependency as well.

**Comment by nico** [comment]
I think #16 (just merged) fixes this.

**Comment by loretoparisi** [comment]
@nico thanks, let me check it out.

**Comment by loretoparisi** [comment]
Trying here, but with some issues https://github.com/google/cld3/issues/23

**Comment by loretoparisi** [comment]
I was finally able to compile the CLD3 static library, see here https://github.com/google/cld3/issues/23
Closing.
