### ISSUE TITLE
Many Chinese pages are identified as English

### ISSUE THREAD

**Issue by vitaly-zdanevich** [google/cld3#14]
For example http://www.zgshige.com/c/2018-12-19/7995447.shtml

**Comment by jasonriesa** [comment]
As with issue #17, I cannot replicate this either. Chrome with CLD3 correctly detects this page as zh-Hans.

If you are scraping web content and applying CLD3, make sure you remove HTML and make sure you are sending UTF-8 content and text in no other encoding to CLD3.

**Comment by loretoparisi** [comment]
@jasonriesa to be sure, it detects that text as `zh`, because it has only `zh-hans` but not `zh-hant`, so when I try

```
"把中坛元帅固定在神轿",
"親愛的牽起你的手 並將他們放在我手中",
```

it give me out both `zh`, while the first is `zh-hans`, but the second is actually `zh-hant`.
