### ISSUE TITLE
Hindi identified as English

### ISSUE THREAD

**Issue by vitaly-zdanevich** [google/cld3#17]
For example on this page:
https://orientalinsurance.org.in/hi/web/guest/privacy-policy

**Comment by jasonriesa** [comment]
I cannot replicate the issue for the URL you mentioned. 
In Chrome, if you:
1. Navigate to chrome://translate-internals
2. Open the Detection Logs tab
3. Open a new tab with your URL https://orientalinsurance.org.in/hi/web/guest/privacy-policy
4. Go back to the Detection Logs tab
It shows CLD3 detects the page correctly as Hindi.
