### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by ekalchev** [google/cld3#42]
What is the right way of using NNetLanguageIdentifier in concurrently with threads?

I thought that if I create separate instance for each thread it should be ok, but I start getting access violation exceptions in NNetLanguageIdentifier constructor when threads are running concurrently. 
I was able to solve that by adding a global lock but I wonder what is the best way to use the code concurrently.
May be if I create single instance of NNetLanguageIdentifier and share it between threads should be ok? Thoughts?

**Comment by WilliamTambellini** [comment]
@ekalchev Watchup, NNetLanguageIdentifier is not thread safe.
I ended up creating 1 instance per thread: seems to use only 4MB per instance, the NN being very small.
Example:
thread_local NNetLanguageIdentifier langId(minNumBytes, maxNumBytes);
