### ISSUE TITLE
Training set

### ISSUE THREAD

**Issue by fabiospampinato** [google/cld3#73]
Is the training set that was used to train CLD3 available somewhere? Alternatively, and a bit off-topic, is there a sort of standard or very good dataset used for writing a language classifier like this one?

**Comment by chiarcos** [comment]
Not really. Wikipedia is a good starting point, and you can get relatively clean (partial) extracts for many languages from, say, https://corpora.uni-leipzig.de/en. Another good source for rare languages are Bibles. A few years ago, [biola.edu](https://www.biola.edu/talbot/unbound) was a great source for these.They disabled their service by now, but Google will give you others ;)

**Comment by fabiospampinato** [comment]
Thank you 👍
